2022-02-12 05:08:01,075 - urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f764ce6e760>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/8d4980b2610160e92e5fe9147f63472a/url
2022-02-12 05:08:01,076 - urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f764ce6e8e0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/8d4980b2610160e92e5fe9147f63472a/url
2022-02-12 05:08:01,076 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f764ce6eee0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/8d4980b2610160e92e5fe9147f63472a/url
2022-02-12 05:08:01,078 - urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f764ce84370>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/8d4980b2610160e92e5fe9147f63472a
2022-02-12 05:08:01,078 - urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f764ce84370>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/8d4980b2610160e92e5fe9147f63472a
2022-02-12 05:08:01,079 - urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f764ce844f0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/8d4980b2610160e92e5fe9147f63472a
2022-02-12 05:08:01,079 - urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f764ce844f0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/8d4980b2610160e92e5fe9147f63472a
2022-02-12 05:08:01,079 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f764ce84640>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/8d4980b2610160e92e5fe9147f63472a
2022-02-12 05:08:01,079 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f764ce84640>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/8d4980b2610160e92e5fe9147f63472a
